// Emoji puzzle data structures with difficulty tiers

export interface EmojiItem {
  word: string;
  emoji: string;
  difficulty: 'easy' | 'medium' | 'hard';
}

// EASY tier - Common objects, food, basic concepts (200+ items)
const easyItems: EmojiItem[] = [
  // Food & Drinks
  { word: 'apple', emoji: '🍎', difficulty: 'easy' },
  { word: 'banana', emoji: '🍌', difficulty: 'easy' },
  { word: 'pizza', emoji: '🍕', difficulty: 'easy' },
  { word: 'burger', emoji: '🍔', difficulty: 'easy' },
  { word: 'hot', emoji: '🔥', difficulty: 'easy' },
  { word: 'dog', emoji: '🐕', difficulty: 'easy' },
  { word: 'cat', emoji: '🐱', difficulty: 'easy' },
  { word: 'water', emoji: '💧', difficulty: 'easy' },
  { word: 'coffee', emoji: '☕', difficulty: 'easy' },
  { word: 'cake', emoji: '🍰', difficulty: 'easy' },
  { word: 'bread', emoji: '🍞', difficulty: 'easy' },
  { word: 'cheese', emoji: '🧀', difficulty: 'easy' },
  { word: 'egg', emoji: '🥚', difficulty: 'easy' },
  { word: 'milk', emoji: '🥛', difficulty: 'easy' },
  { word: 'ice', emoji: '🧊', difficulty: 'easy' },
  { word: 'cream', emoji: '🍦', difficulty: 'easy' },
  { word: 'candy', emoji: '🍬', difficulty: 'easy' },
  { word: 'cookie', emoji: '🍪', difficulty: 'easy' },
  { word: 'pop', emoji: '🎈', difficulty: 'easy' },
  { word: 'corn', emoji: '🌽', difficulty: 'easy' },
  
  // Animals
  { word: 'bee', emoji: '🐝', difficulty: 'easy' },
  { word: 'bird', emoji: '🐦', difficulty: 'easy' },
  { word: 'fish', emoji: '🐟', difficulty: 'easy' },
  { word: 'bear', emoji: '🐻', difficulty: 'easy' },
  { word: 'pig', emoji: '🐷', difficulty: 'easy' },
  { word: 'cow', emoji: '🐄', difficulty: 'easy' },
  { word: 'monkey', emoji: '🐵', difficulty: 'easy' },
  { word: 'lion', emoji: '🦁', difficulty: 'easy' },
  { word: 'tiger', emoji: '🐯', difficulty: 'easy' },
  { word: 'mouse', emoji: '🐭', difficulty: 'easy' },
  { word: 'rabbit', emoji: '🐰', difficulty: 'easy' },
  { word: 'frog', emoji: '🐸', difficulty: 'easy' },
  { word: 'duck', emoji: '🦆', difficulty: 'easy' },
  { word: 'chicken', emoji: '🐔', difficulty: 'easy' },
  { word: 'penguin', emoji: '🐧', difficulty: 'easy' },
  { word: 'bug', emoji: '🐛', difficulty: 'easy' },
  { word: 'bat', emoji: '🦇', difficulty: 'easy' },
  { word: 'wolf', emoji: '🐺', difficulty: 'easy' },
  
  // Objects
  { word: 'ball', emoji: '⚽', difficulty: 'easy' },
  { word: 'book', emoji: '📖', difficulty: 'easy' },
  { word: 'car', emoji: '🚗', difficulty: 'easy' },
  { word: 'house', emoji: '🏠', difficulty: 'easy' },
  { word: 'tree', emoji: '🌲', difficulty: 'easy' },
  { word: 'flower', emoji: '🌸', difficulty: 'easy' },
  { word: 'sun', emoji: '☀️', difficulty: 'easy' },
  { word: 'moon', emoji: '🌙', difficulty: 'easy' },
  { word: 'star', emoji: '⭐', difficulty: 'easy' },
  { word: 'phone', emoji: '📱', difficulty: 'easy' },
  { word: 'key', emoji: '🔑', difficulty: 'easy' },
  { word: 'door', emoji: '🚪', difficulty: 'easy' },
  { word: 'bell', emoji: '🔔', difficulty: 'easy' },
  { word: 'light', emoji: '💡', difficulty: 'easy' },
  { word: 'fire', emoji: '🔥', difficulty: 'easy' },
  { word: 'snow', emoji: '❄️', difficulty: 'easy' },
  { word: 'rain', emoji: '🌧️', difficulty: 'easy' },
  { word: 'bow', emoji: '🎀', difficulty: 'easy' },
  { word: 'ring', emoji: '💍', difficulty: 'easy' },
  { word: 'crown', emoji: '👑', difficulty: 'easy' },
  { word: 'hat', emoji: '🎩', difficulty: 'easy' },
  { word: 'shirt', emoji: '👕', difficulty: 'easy' },
  { word: 'shoe', emoji: '👟', difficulty: 'easy' },
  { word: 'glasses', emoji: '👓', difficulty: 'easy' },
  { word: 'watch', emoji: '⌚', difficulty: 'easy' },
  { word: 'bag', emoji: '💼', difficulty: 'easy' },
  { word: 'pen', emoji: '🖊️', difficulty: 'easy' },
  { word: 'paper', emoji: '📄', difficulty: 'easy' },
  { word: 'rock', emoji: '🪨', difficulty: 'easy' },
  { word: 'bomb', emoji: '💣', difficulty: 'easy' },
  { word: 'gun', emoji: '🔫', difficulty: 'easy' },
  { word: 'knife', emoji: '🔪', difficulty: 'easy' },
  { word: 'fork', emoji: '🍴', difficulty: 'easy' },
  { word: 'spoon', emoji: '🥄', difficulty: 'easy' },
  { word: 'nail', emoji: '💅', difficulty: 'easy' },
  { word: 'tooth', emoji: '🦷', difficulty: 'easy' },
  { word: 'brush', emoji: '🪥', difficulty: 'easy' },
  { word: 'soap', emoji: '🧼', difficulty: 'easy' },
  { word: 'bath', emoji: '🛁', difficulty: 'easy' },
  { word: 'bed', emoji: '🛏️', difficulty: 'easy' },
  { word: 'chair', emoji: '🪑', difficulty: 'easy' },
  { word: 'table', emoji: '🪑', difficulty: 'easy' },
  { word: 'lock', emoji: '🔒', difficulty: 'easy' },
  { word: 'chain', emoji: '⛓️', difficulty: 'easy' },
  { word: 'link', emoji: '🔗', difficulty: 'easy' },
  { word: 'pin', emoji: '📌', difficulty: 'easy' },
  { word: 'clip', emoji: '📎', difficulty: 'easy' },
  { word: 'tape', emoji: '📼', difficulty: 'easy' },
  { word: 'box', emoji: '📦', difficulty: 'easy' },
  { word: 'gift', emoji: '🎁', difficulty: 'easy' },
  { word: 'party', emoji: '🎉', difficulty: 'easy' },
  { word: 'birthday', emoji: '🎂', difficulty: 'easy' },
  { word: 'music', emoji: '🎵', difficulty: 'easy' },
  { word: 'note', emoji: '🎶', difficulty: 'easy' },
  { word: 'flag', emoji: '🚩', difficulty: 'easy' },
  { word: 'mail', emoji: '✉️', difficulty: 'easy' },
  { word: 'money', emoji: '💰', difficulty: 'easy' },
  { word: 'dollar', emoji: '💵', difficulty: 'easy' },
  { word: 'coin', emoji: '🪙', difficulty: 'easy' },
  { word: 'gem', emoji: '💎', difficulty: 'easy' },
  { word: 'crystal', emoji: '🔮', difficulty: 'easy' },
  { word: 'magic', emoji: '✨', difficulty: 'easy' },
  { word: 'wand', emoji: '🪄', difficulty: 'easy' },
];

// MEDIUM tier - Actions, emotions, compound words (150+ items)
const mediumItems: EmojiItem[] = [
  // Body parts & emotions
  { word: 'eye', emoji: '👁️', difficulty: 'medium' },
  { word: 'hand', emoji: '✋', difficulty: 'medium' },
  { word: 'foot', emoji: '🦶', difficulty: 'medium' },
  { word: 'ear', emoji: '👂', difficulty: 'medium' },
  { word: 'nose', emoji: '👃', difficulty: 'medium' },
  { word: 'brain', emoji: '🧠', difficulty: 'medium' },
  { word: 'heart', emoji: '❤️', difficulty: 'medium' },
  { word: 'break', emoji: '💔', difficulty: 'medium' },
  { word: 'love', emoji: '💕', difficulty: 'medium' },
  { word: 'kiss', emoji: '💋', difficulty: 'medium' },
  { word: 'anger', emoji: '😠', difficulty: 'medium' },
  { word: 'cry', emoji: '😢', difficulty: 'medium' },
  { word: 'laugh', emoji: '😂', difficulty: 'medium' },
  { word: 'sleep', emoji: '😴', difficulty: 'medium' },
  { word: 'dream', emoji: '💭', difficulty: 'medium' },
  { word: 'think', emoji: '🤔', difficulty: 'medium' },
  { word: 'sick', emoji: '🤒', difficulty: 'medium' },
  { word: 'head', emoji: '🗣️', difficulty: 'medium' },
  { word: 'ache', emoji: '🤕', difficulty: 'medium' },
  
  // Actions & verbs
  { word: 'run', emoji: '🏃', difficulty: 'medium' },
  { word: 'walk', emoji: '🚶', difficulty: 'medium' },
  { word: 'jump', emoji: '🦘', difficulty: 'medium' },
  { word: 'dance', emoji: '💃', difficulty: 'medium' },
  { word: 'sing', emoji: '🎤', difficulty: 'medium' },
  { word: 'play', emoji: '🎮', difficulty: 'medium' },
  { word: 'work', emoji: '💼', difficulty: 'medium' },
  { word: 'read', emoji: '📚', difficulty: 'medium' },
  { word: 'write', emoji: '✍️', difficulty: 'medium' },
  { word: 'draw', emoji: '🎨', difficulty: 'medium' },
  { word: 'paint', emoji: '🖌️', difficulty: 'medium' },
  { word: 'cut', emoji: '✂️', difficulty: 'medium' },
  { word: 'paste', emoji: '📋', difficulty: 'medium' },
  { word: 'fly', emoji: '✈️', difficulty: 'medium' },
  { word: 'sail', emoji: '⛵', difficulty: 'medium' },
  { word: 'boat', emoji: '🚤', difficulty: 'medium' },
  { word: 'ship', emoji: '🚢', difficulty: 'medium' },
  { word: 'rocket', emoji: '🚀', difficulty: 'medium' },
  { word: 'space', emoji: '🌌', difficulty: 'medium' },
  { word: 'alien', emoji: '👽', difficulty: 'medium' },
  { word: 'robot', emoji: '🤖', difficulty: 'medium' },
  { word: 'ghost', emoji: '👻', difficulty: 'medium' },
  { word: 'devil', emoji: '😈', difficulty: 'medium' },
  { word: 'angel', emoji: '😇', difficulty: 'medium' },
  { word: 'monster', emoji: '👹', difficulty: 'medium' },
  { word: 'clown', emoji: '🤡', difficulty: 'medium' },
  { word: 'cowboy', emoji: '🤠', difficulty: 'medium' },
  { word: 'detective', emoji: '🕵️', difficulty: 'medium' },
  { word: 'guard', emoji: '💂', difficulty: 'medium' },
  { word: 'ninja', emoji: '🥷', difficulty: 'medium' },
  
  // Nature & weather
  { word: 'storm', emoji: '⛈️', difficulty: 'medium' },
  { word: 'thunder', emoji: '⚡', difficulty: 'medium' },
  { word: 'bolt', emoji: '🔩', difficulty: 'medium' },
  { word: 'cloud', emoji: '☁️', difficulty: 'medium' },
  { word: 'rainbow', emoji: '🌈', difficulty: 'medium' },
  { word: 'wind', emoji: '💨', difficulty: 'medium' },
  { word: 'wave', emoji: '🌊', difficulty: 'medium' },
  { word: 'ocean', emoji: '🌊', difficulty: 'medium' },
  { word: 'mountain', emoji: '⛰️', difficulty: 'medium' },
  { word: 'volcano', emoji: '🌋', difficulty: 'medium' },
  { word: 'desert', emoji: '🏜️', difficulty: 'medium' },
  { word: 'island', emoji: '🏝️', difficulty: 'medium' },
  { word: 'forest', emoji: '🌲', difficulty: 'medium' },
  { word: 'leaf', emoji: '🍃', difficulty: 'medium' },
  { word: 'seed', emoji: '🌱', difficulty: 'medium' },
  { word: 'plant', emoji: '🪴', difficulty: 'medium' },
  { word: 'cactus', emoji: '🌵', difficulty: 'medium' },
  { word: 'rose', emoji: '🌹', difficulty: 'medium' },
  { word: 'tulip', emoji: '🌷', difficulty: 'medium' },
  { word: 'mushroom', emoji: '🍄', difficulty: 'medium' },
  
  // Time & calendar
  { word: 'time', emoji: '⏰', difficulty: 'medium' },
  { word: 'clock', emoji: '🕐', difficulty: 'medium' },
  { word: 'hour', emoji: '⌛', difficulty: 'medium' },
  { word: 'glass', emoji: '🥃', difficulty: 'medium' },
  { word: 'minute', emoji: '⏱️', difficulty: 'medium' },
  { word: 'second', emoji: '⏲️', difficulty: 'medium' },
  { word: 'calendar', emoji: '📅', difficulty: 'medium' },
  { word: 'date', emoji: '📆', difficulty: 'medium' },
  { word: 'day', emoji: '🌞', difficulty: 'medium' },
  { word: 'night', emoji: '🌛', difficulty: 'medium' },
  { word: 'morning', emoji: '🌅', difficulty: 'medium' },
  { word: 'evening', emoji: '🌆', difficulty: 'medium' },
  { word: 'sunset', emoji: '🌇', difficulty: 'medium' },
  
  // Sports & games
  { word: 'soccer', emoji: '⚽', difficulty: 'medium' },
  { word: 'basket', emoji: '🏀', difficulty: 'medium' },
  { word: 'tennis', emoji: '🎾', difficulty: 'medium' },
  { word: 'golf', emoji: '⛳', difficulty: 'medium' },
  { word: 'baseball', emoji: '⚾', difficulty: 'medium' },
  { word: 'football', emoji: '🏈', difficulty: 'medium' },
  { word: 'bowl', emoji: '🎳', difficulty: 'medium' },
  { word: 'pool', emoji: '🎱', difficulty: 'medium' },
  { word: 'dart', emoji: '🎯', difficulty: 'medium' },
  { word: 'board', emoji: '🎲', difficulty: 'medium' },
  { word: 'game', emoji: '🎮', difficulty: 'medium' },
  { word: 'dice', emoji: '🎲', difficulty: 'medium' },
  { word: 'card', emoji: '🃏', difficulty: 'medium' },
  { word: 'chess', emoji: '♟️', difficulty: 'medium' },
  { word: 'trophy', emoji: '🏆', difficulty: 'medium' },
  { word: 'medal', emoji: '🏅', difficulty: 'medium' },
  { word: 'gold', emoji: '🥇', difficulty: 'medium' },
  { word: 'silver', emoji: '🥈', difficulty: 'medium' },
  { word: 'bronze', emoji: '🥉', difficulty: 'medium' },
  
  // Food combinations
  { word: 'butter', emoji: '🧈', difficulty: 'medium' },
  { word: 'peanut', emoji: '🥜', difficulty: 'medium' },
  { word: 'jelly', emoji: '🍇', difficulty: 'medium' },
  { word: 'jam', emoji: '🍓', difficulty: 'medium' },
  { word: 'honey', emoji: '🍯', difficulty: 'medium' },
  { word: 'syrup', emoji: '🍁', difficulty: 'medium' },
  { word: 'sauce', emoji: '🥫', difficulty: 'medium' },
  { word: 'ketchup', emoji: '🍅', difficulty: 'medium' },
  { word: 'mustard', emoji: '🌭', difficulty: 'medium' },
  { word: 'salt', emoji: '🧂', difficulty: 'medium' },
  { word: 'pepper', emoji: '🌶️', difficulty: 'medium' },
  { word: 'sugar', emoji: '🍬', difficulty: 'medium' },
  { word: 'spice', emoji: '🧂', difficulty: 'medium' },
  { word: 'rice', emoji: '🍚', difficulty: 'medium' },
  { word: 'noodle', emoji: '🍜', difficulty: 'medium' },
  { word: 'soup', emoji: '🍲', difficulty: 'medium' },
  { word: 'stew', emoji: '🥘', difficulty: 'medium' },
  { word: 'meat', emoji: '🥩', difficulty: 'medium' },
  { word: 'bone', emoji: '🦴', difficulty: 'medium' },
  { word: 'bacon', emoji: '🥓', difficulty: 'medium' },
  { word: 'ham', emoji: '🍖', difficulty: 'medium' },
  { word: 'sausage', emoji: '🌭', difficulty: 'medium' },
];

// HARD tier - Abstract concepts, idioms, puns (100+ items)
const hardItems: EmojiItem[] = [
  // Abstract concepts
  { word: 'peace', emoji: '☮️', difficulty: 'hard' },
  { word: 'war', emoji: '⚔️', difficulty: 'hard' },
  { word: 'battle', emoji: '⚔️', difficulty: 'hard' },
  { word: 'fight', emoji: '🥊', difficulty: 'hard' },
  { word: 'winner', emoji: '🏆', difficulty: 'hard' },
  { word: 'loser', emoji: '💔', difficulty: 'hard' },
  { word: 'victory', emoji: '✌️', difficulty: 'hard' },
  { word: 'defeat', emoji: '🏳️', difficulty: 'hard' },
  { word: 'power', emoji: '💪', difficulty: 'hard' },
  { word: 'weak', emoji: '🤷', difficulty: 'hard' },
  { word: 'strong', emoji: '💪', difficulty: 'hard' },
  { word: 'smart', emoji: '🧠', difficulty: 'hard' },
  { word: 'dumb', emoji: '🤪', difficulty: 'hard' },
  { word: 'wise', emoji: '🦉', difficulty: 'hard' },
  { word: 'fool', emoji: '🤡', difficulty: 'hard' },
  { word: 'king', emoji: '🤴', difficulty: 'hard' },
  { word: 'queen', emoji: '👸', difficulty: 'hard' },
  { word: 'prince', emoji: '🤴', difficulty: 'hard' },
  { word: 'princess', emoji: '👸', difficulty: 'hard' },
  { word: 'knight', emoji: '🛡️', difficulty: 'hard' },
  { word: 'dragon', emoji: '🐉', difficulty: 'hard' },
  { word: 'sword', emoji: '⚔️', difficulty: 'hard' },
  { word: 'shield', emoji: '🛡️', difficulty: 'hard' },
  { word: 'armor', emoji: '🦾', difficulty: 'hard' },
  { word: 'castle', emoji: '🏰', difficulty: 'hard' },
  { word: 'tower', emoji: '🗼', difficulty: 'hard' },
  { word: 'bridge', emoji: '🌉', difficulty: 'hard' },
  { word: 'gate', emoji: '🚪', difficulty: 'hard' },
  { word: 'path', emoji: '🛤️', difficulty: 'hard' },
  { word: 'road', emoji: '🛣️', difficulty: 'hard' },
  { word: 'street', emoji: '🛤️', difficulty: 'hard' },
  { word: 'highway', emoji: '🛣️', difficulty: 'hard' },
  
  // Idiom components
  { word: 'cold', emoji: '🥶', difficulty: 'hard' },
  { word: 'shoulder', emoji: '🤷', difficulty: 'hard' },
  { word: 'piece', emoji: '🧩', difficulty: 'hard' },
  { word: 'mind', emoji: '🧠', difficulty: 'hard' },
  { word: 'soul', emoji: '👻', difficulty: 'hard' },
  { word: 'spirit', emoji: '✨', difficulty: 'hard' },
  { word: 'body', emoji: '🧘', difficulty: 'hard' },
  { word: 'blood', emoji: '🩸', difficulty: 'hard' },
  { word: 'sweat', emoji: '💦', difficulty: 'hard' },
  { word: 'tear', emoji: '😭', difficulty: 'hard' },
  { word: 'smile', emoji: '😊', difficulty: 'hard' },
  { word: 'grin', emoji: '😁', difficulty: 'hard' },
  { word: 'frown', emoji: '☹️', difficulty: 'hard' },
  { word: 'wink', emoji: '😉', difficulty: 'hard' },
  { word: 'shock', emoji: '😱', difficulty: 'hard' },
  { word: 'surprise', emoji: '😲', difficulty: 'hard' },
  { word: 'fear', emoji: '😨', difficulty: 'hard' },
  { word: 'scream', emoji: '😱', difficulty: 'hard' },
  { word: 'yell', emoji: '📣', difficulty: 'hard' },
  { word: 'shout', emoji: '📢', difficulty: 'hard' },
  { word: 'whisper', emoji: '🤫', difficulty: 'hard' },
  { word: 'quiet', emoji: '🤫', difficulty: 'hard' },
  { word: 'silent', emoji: '🔇', difficulty: 'hard' },
  { word: 'loud', emoji: '🔊', difficulty: 'hard' },
  { word: 'sound', emoji: '🔊', difficulty: 'hard' },
  { word: 'noise', emoji: '📢', difficulty: 'hard' },
  
  // Complex objects
  { word: 'tool', emoji: '🔧', difficulty: 'hard' },
  { word: 'wrench', emoji: '🔧', difficulty: 'hard' },
  { word: 'hammer', emoji: '🔨', difficulty: 'hard' },
  { word: 'saw', emoji: '🪚', difficulty: 'hard' },
  { word: 'drill', emoji: '🔩', difficulty: 'hard' },
  { word: 'screw', emoji: '🔩', difficulty: 'hard' },
  { word: 'driver', emoji: '🪛', difficulty: 'hard' },
  { word: 'gear', emoji: '⚙️', difficulty: 'hard' },
  { word: 'wheel', emoji: '🎡', difficulty: 'hard' },
  { word: 'axle', emoji: '🛞', difficulty: 'hard' },
  { word: 'engine', emoji: '🔧', difficulty: 'hard' },
  { word: 'motor', emoji: '⚙️', difficulty: 'hard' },
  { word: 'machine', emoji: '🤖', difficulty: 'hard' },
  { word: 'computer', emoji: '💻', difficulty: 'hard' },
  { word: 'laptop', emoji: '💻', difficulty: 'hard' },
  { word: 'keyboard', emoji: '⌨️', difficulty: 'hard' },
  { word: 'mouse', emoji: '🖱️', difficulty: 'hard' },
  { word: 'screen', emoji: '🖥️', difficulty: 'hard' },
  { word: 'monitor', emoji: '🖥️', difficulty: 'hard' },
  { word: 'camera', emoji: '📷', difficulty: 'hard' },
  { word: 'video', emoji: '📹', difficulty: 'hard' },
  { word: 'photo', emoji: '📸', difficulty: 'hard' },
  { word: 'picture', emoji: '🖼️', difficulty: 'hard' },
  { word: 'frame', emoji: '🖼️', difficulty: 'hard' },
  { word: 'mirror', emoji: '🪞', difficulty: 'hard' },
  { word: 'window', emoji: '🪟', difficulty: 'hard' },
  { word: 'curtain', emoji: '🪟', difficulty: 'hard' },
  { word: 'blind', emoji: '🦯', difficulty: 'hard' },
  { word: 'shade', emoji: '😎', difficulty: 'hard' },
  { word: 'shadow', emoji: '👤', difficulty: 'hard' },
  { word: 'dark', emoji: '🌑', difficulty: 'hard' },
  { word: 'bright', emoji: '🌟', difficulty: 'hard' },
  { word: 'shine', emoji: '✨', difficulty: 'hard' },
  { word: 'glow', emoji: '🌟', difficulty: 'hard' },
  { word: 'spark', emoji: '✨', difficulty: 'hard' },
  { word: 'flash', emoji: '⚡', difficulty: 'hard' },
  { word: 'beam', emoji: '💡', difficulty: 'hard' },
  { word: 'ray', emoji: '☀️', difficulty: 'hard' },
  
  // Pun-friendly words
  { word: 'sage', emoji: '🌿', difficulty: 'hard' },
  { word: 'thyme', emoji: '🌿', difficulty: 'hard' },
  { word: 'mint', emoji: '🌿', difficulty: 'hard' },
  { word: 'basil', emoji: '🌿', difficulty: 'hard' },
  { word: 'berry', emoji: '🍓', difficulty: 'hard' },
  { word: 'cherry', emoji: '🍒', difficulty: 'hard' },
  { word: 'peach', emoji: '🍑', difficulty: 'hard' },
  { word: 'plum', emoji: '🍑', difficulty: 'hard' },
  { word: 'grape', emoji: '🍇', difficulty: 'hard' },
  { word: 'melon', emoji: '🍉', difficulty: 'hard' },
  { word: 'orange', emoji: '🍊', difficulty: 'hard' },
  { word: 'lemon', emoji: '🍋', difficulty: 'hard' },
  { word: 'lime', emoji: '🍋', difficulty: 'hard' },
  { word: 'coconut', emoji: '🥥', difficulty: 'hard' },
  { word: 'nut', emoji: '🥜', difficulty: 'hard' },
  { word: 'shell', emoji: '🐚', difficulty: 'hard' },
  { word: 'pearl', emoji: '🦪', difficulty: 'hard' },
  { word: 'oyster', emoji: '🦪', difficulty: 'hard' },
  { word: 'clam', emoji: '🦪', difficulty: 'hard' },
  { word: 'crab', emoji: '🦀', difficulty: 'hard' },
  { word: 'lobster', emoji: '🦞', difficulty: 'hard' },
  { word: 'shrimp', emoji: '🦐', difficulty: 'hard' },
  { word: 'squid', emoji: '🦑', difficulty: 'hard' },
  { word: 'octopus', emoji: '🐙', difficulty: 'hard' },
  { word: 'whale', emoji: '🐋', difficulty: 'hard' },
  { word: 'dolphin', emoji: '🐬', difficulty: 'hard' },
  { word: 'shark', emoji: '🦈', difficulty: 'hard' },
  { word: 'seal', emoji: '🦭', difficulty: 'hard' },
];

// All items combined
export const allItems: EmojiItem[] = [...easyItems, ...mediumItems, ...hardItems];

// Get items by difficulty
export function getItemsByDifficulty(difficulty: 'easy' | 'medium' | 'hard'): EmojiItem[] {
  return allItems.filter(item => item.difficulty === difficulty);
}

// Get random items from a specific tier
export function getRandomItemsFromTier(
  tier: 'easy' | 'medium' | 'hard',
  count: number
): EmojiItem[] {
  const tierItems = getItemsByDifficulty(tier);
  const shuffled = [...tierItems].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, count);
}
